version: '3'
services:
  web:
    image: nginx
    ports:
      - 8080:80
    volumes:
      - ../../../../:/var/www/html
      - ./nginx/conf.d:/etc/nginx/conf.d
    links:
      - app
    environment:
      - VIRTUAL_HOST=raft.docker
      - HTTPS_METHOD=noredirect

  queue:
    image: loganhenson/tylerwebdev_queue
    links:
      - redis:redis
      - database:database
    depends_on:
      - database
    volumes:
      - ../../../../:/var/www/html

  app:
    image: loganhenson/tylerwebdev_php
    links:
      - redis:redis
      - database:database
    depends_on:
      - database
    volumes:
      - ../../../../:/var/www/html

  redis:
    image: redis

  database:
    image: mariadb
    ports:
      - 3300:3306
    environment:
      - MYSQL_DATABASE=database
      - MYSQL_ROOT_PASSWORD=password
